### ISSUE TITLE
Back of the envelope for data volume

### ISSUE THREAD

**Issue by roelaaij** [roelaaij/lhcb-hlt2-monitoring#2]
We need to get an idea of data volume. Make a mock histogram with ROOT, put it in a TFileBuffer and check how much space it takes. Multiply by the number of processes (400 + 800 )\* 28 + 800 \* 36 = 70000 divided by update interval (10s??) to know the total input bandwidth to the "adder".

**Comment by roelaaij** [comment]
Alternative data format:
- TCK
- unsigned integer to indentify histograms.
- vector of long for histograms

The algorithm that creates the histograms uses either the HltANNSvc to translate the names into numbers or a property. The receiving process then uses TCK utils to get back the names.

Check how much data this would result in.

**Comment by roelaaij** [comment]
The TFileBuffer takes nearly a kiB for a single histogram, versus 90 bytes for the boost serialized one. I think that makes it clear we'll go that way.

**Comment by kdungs** [comment]
Might also need to add a start time (`std::size_t` since it's an index to the hist?) in case we just want to send chunks.

**Comment by roelaaij** [comment]
Sure, 4 bytes will make little difference :)

**Comment by roelaaij** [comment]
With 0.1 kiB per histogram, 70k processes and an update interval of 10 s the total traffic is close to 70 MiB. This is very doable even without intermediate per/subfarm adders; we'll still need those to keep the number of connections manageable.

**Comment by roelaaij** [comment]
Data volume is manageable, we should not use TFileBuffer due to way too much overhead. Closing ths issue.
